# Generated by Django 3.1.3 on 2020-11-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201109_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='API.moviedata'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='API.moviedata'),
        ),
    ]
