# Generated by Django 3.1.3 on 2020-11-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20201109_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
