# Generated by Django 3.1.3 on 2020-11-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201110_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, related_name='comm', to='API.moviedata'),
        ),
    ]
