# Generated by Django 3.1.3 on 2020-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20201110_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
