# Generated by Django 3.1.3 on 2020-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20201111_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='boxoffice',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='country',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='director',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='dvd',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='genre',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='imdbid',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='imdbrating',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='imdbvotes',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='language',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='metascore',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='poster',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='production',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='rated',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='released',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='response',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='runtime',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='type',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='website',
            field=models.CharField(max_length=512),
        ),
    ]
